import { eq } from "drizzle-orm";
import fs from "node:fs";
import { SEASON } from "../lib/config";
import { createDb } from "../lib/db";
import { events, seasons, sessions } from "../lib/db/schema";
import { fetchAfter, inZone } from "../lib/ingest/schedule";

/**
 * Writes .github/workflows/sync.yml with one cron entry per remaining scoring
 * session, fired two hours after that race is expected to end.
 *
 * Generated rather than hand-written: the times come from the calendar in the
 * database, so they cannot drift away from the real schedule. Re-run after the
 * session timetable firms up (`npm run gen:workflow`).
 */
const db = createDb();
const season = db.select().from(seasons).where(eq(seasons.year, SEASON)).get()!;
const calendar = db.select().from(events).where(eq(events.seasonId, season.id)).all();
const eventById = new Map(calendar.map((e) => [e.id, e]));
const now = new Date();

const upcoming = db
  .select()
  .from(sessions)
  .all()
  .filter((s) => s.definitive && eventById.has(s.eventId))
  .map((s) => {
    const event = eventById.get(s.eventId)!;
    return {
      event,
      type: s.type,
      at: fetchAfter(
        { id: s.id, type: s.type, dateUtc: s.dateUtc, status: s.status },
        { dateStart: event.dateStart, dateEnd: event.dateEnd }
      )
    };
  })
  .filter((s) => s.at > now)
  .sort((a, b) => a.at.getTime() - b.at.getTime());

const lines = upcoming.map(({ event, type, at }) => {
  const cron = `${at.getUTCMinutes()} ${at.getUTCHours()} ${at.getUTCDate()} ${at.getUTCMonth() + 1} *`;
  const label = `R${event.round} ${event.shortName} ${type} — ${inZone(at, "Asia/Kolkata")} IST`;
  return `    # ${label}\n    - cron: "${cron}"`;
});

const yaml = `name: sync

# Ingests results two hours after each race is expected to end.
#
# GENERATED by \`npm run gen:workflow\` from the calendar in phoenix93.db.
# Do not hand-edit the cron list; re-run the generator instead.
#
# GitHub cron is UTC and can be delayed under load, so two safety nets follow
# the exact times: an hourly sweep across race weekends, and a daily backstop.
# Every run is idempotent and only ingests sessions motogp.com reports FINISHED,
# so an extra run costs one HTTP request and changes nothing.

on:
  workflow_dispatch:
  schedule:
${lines.join("\n")}

    # Safety net: hourly across race weekends (Sat/Sun/Mon, 14:00-23:59 UTC)
    - cron: "5 14-23 * * 6,0,1"
    # Daily backstop at 20:00 IST
    - cron: "30 14 * * *"

concurrency:
  group: sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Ingest any finished session
        run: npm run sync
      - name: Verify the championship still reconciles with motogp.com
        run: npm run verify
      - name: Commit new results
        run: |
          if [ -n "$(git status --porcelain phoenix93.db)" ]; then
            git config user.name "phoenix93-sync"
            git config user.email "sync@users.noreply.github.com"
            git add phoenix93.db
            git commit -m "sync: ingest results ($(date -u +%Y-%m-%dT%H:%MZ))"
            git push
          else
            echo "Nothing new to ingest."
          fi
`;

fs.writeFileSync(".github/workflows/sync.yml", yaml);
console.log(`\n  Wrote .github/workflows/sync.yml with ${upcoming.length} exact session triggers:\n`);
for (const { event, type, at } of upcoming) {
  console.log(`    R${String(event.round).padStart(2)} ${event.shortName.padEnd(4)} ${type.padEnd(3)}  ${at.toISOString().slice(0, 16)}Z   ${inZone(at, "Asia/Kolkata")} IST`);
}
console.log();
